FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

RUN npm install -g typescript

COPY .env .env

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "node","dist/index.js" ]

